EXECUTE NOTEBOOK PROJECT DEMO_DB.DEV_SCHEMA.DEMO_PIPELINES_NP
  MAIN_FILE = '01_load_excel_files.ipynb'
  COMPUTE_POOL = 'SYSTEM_COMPUTE_POOL_CPU'
  QUERY_WAREHOUSE = 'DEFAULT_WH'
  RUNTIME = 'V2.5-CPU-PY3.12'
    ARTIFACT_REPOSITORIES = (snowflake.snowpark.pypi_shared_repository)
  REQUIREMENTS_FILE = 'requirements.txt';
            

SELECT *
FROM SNOWFLAKE.TELEMETRY.EVENTS
-- WHERE RESOURCE_ATTRIBUTES:"snow.service.name"::string = 'NB_NON_INTERACTIVE_1786378262765_1X2C3YH'
ORDER BY TIMESTAMP DESC
-- LIMIT 100;

SHOW ROLES LIKE 'DEMO_ROLE';                    -- should now return a row
SHOW DATABASES LIKE 'DEMO_DB';

SELECT TIMESTAMP,
       RECORD_TYPE,
       VALUE AS log_message,
       RECORD_ATTRIBUTES:"severity_text"::string AS severity
FROM SNOWFLAKE.TELEMETRY.EVENTS
WHERE RESOURCE_ATTRIBUTES:"service.name"::string = 'NB_NON_INTERACTIVE_1786378262765_1X2C3YH'
ORDER BY TIMESTAMP DESC
LIMIT 200;

SELECT TIMESTAMP,
        value,
       RECORD,
       RESOURCE_ATTRIBUTES:"snow.service.name"::string AS service_name
FROM DEMO_DB.INTEGRATIONS.DEMO_EVENTS
WHERE TIMESTAMP > DATEADD(hour, -2, CURRENT_TIMESTAMP()) and service_name = 'NB_NON_INTERACTIVE_1786378262765_1X2C3YH'
ORDER BY TIMESTAMP DESC
LIMIT 200;

SELECT 
    TIMESTAMP,
    VALUE AS LOG_MESSAGE,
    RESOURCE_ATTRIBUTES:"snow.service.name"::string AS SERVICE_NAME,
    RECORD_ATTRIBUTES:"severity_text"::string AS SEVERITY
FROM DEMO_DB.INTEGRATIONS.DEMO_EVENTS
WHERE RECORD_TYPE = 'LOG'
AND RESOURCE_ATTRIBUTES:"snow.service.name" = 'VIVEK_KUSHWAHA_SERVICE_1'
  AND TIMESTAMP > DATEADD(hour, -1, CURRENT_TIMESTAMP())
ORDER BY TIMESTAMP DESC
LIMIT 100;

LIST 'snow://notebook/DEMO_DB.DEV_SCHEMA.DEMO_PIPELINES_NP/versions/live/';

LIST @DEMO_DB.DEV_SCHEMA.NB_DEPLOY_STAGE;